openapi: 3.0.0
info:
  title: Conovel API
  version: 1.0.0
servers:
  - url: /v1
paths:
  /sentences/{sentence_id}:
    get:
      tags:
        - sentences
      operationId: getSentenceById
      summary: "IDで投稿を取得"
      parameters:
        - name: sentence_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: "投稿IDで取得した投稿および関連投稿"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ViewSentence"
        '404':
          description: "投稿が見つからない"
    post:
      tags:
        - sentences
      operationId: postSentence
      summary: "投稿IDの続きの新規投稿を作成"
      parameters:
        - name: sentence_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostSentence"
      responses:
        '201':
          description: "新規投稿の追加に成功"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ViewSentence"
        '400':
          description: "新規投稿の追加に失敗"
  /evaluations/{sentence_id}:
    post:
      tags:
        - evaluations
      operationId: evaluateSentence
      summary: "投稿に対する評価を追加"
      parameters:
        - name: sentence_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EvaluateSentence"
      responses:
        '201':
          description: "評価の追加に成功"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ViewEvaluation"
        '400':
          description: "評価の追加に失敗"
  /novels/:
    get:
      tags:
        - novels
      operationId: getNovels
      summary: "小説一覧を取得"
      responses:
        '200':
          description: "小説一覧"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Novels"
  /novels/{title_id}:
    get:
      tags:
        - novels
      operationId: getNovelById
      summary: "IDで小説の概要を取得"
      parameters:
        - name: title_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: "小説IDで取得した小説"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NovelOverview"
        '404':
          description: "小説が見つからない"
  /users/:
    post:
      tags:
        - users
      operationId: registerUser
      summary: "ユーザー登録"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterUser"
      responses:
        '201':
          description: "ユーザー登録に成功"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegisterUserResult"
        '400':
          description: "ユーザー登録に失敗"
components:
  schemas:
    Sentence:
      type: object
      properties:
        sentence_id:
          type: integer
          format: int64
          description: "投稿の一意のid（この値は他の投稿と重複しない必要があります）"
        sentence:
          type: string
          description: "投稿の本文テキスト"
        sentence_user_id:
          type: integer
          format: int64
          description: "投稿ユーザーのid"
        sentence_user_name:
          type: string
          description: "投稿ユーザーのペンネーム"
        profile_icon_image:
          type: string
          description: "投稿ユーザーアイコン画像のurl"
        evaluation_good_count:
          type: integer
          description: "投稿に対するGood評価の数"
        evaluation_stay_count:
          type: integer
          description: "投稿に対するStay評価の数"
        created_at:
          type: string
          format: date-time
          description: "投稿日時"
        updated_at:
          type: string
          format: date-time
          description: "修正日時"
    Sentences:
      type: array
      items:
        $ref: "#/components/schemas/Sentence"
    ViewSentence:
      type: object
      properties:
        main:
          $ref: "#/components/schemas/Sentence"
        parent:
          $ref: "#/components/schemas/Sentence"
        parentParallel:
          $ref: "#/components/schemas/Sentences"
        children:
          $ref: "#/components/schemas/Sentences"
    PostSentence:
      type: object
      properties:
        parent_sentence_id:
          type: integer
          format: int64
          description: "親投稿のid"
        parent_sentence_user_id:
          type: integer
          format: int64
          description: "親投稿のユーザーid"
        sentence_user_id:
          type: integer
          format: int64
          description: "新投稿のユーザーid"
        sentence:
          type: string
          description: "新投稿の本文テキスト"
    EvaluateSentence:
      type: object
      properties:
        sentence_id:
          type: integer
          format: int64
          description: "評価対象の投稿のID"
        evaluator_user_id:
          type: integer
          format: int64
          description: "評価を行ったユーザーのID"
        evaluation:
          type: string
          enum: [good, bad, stay]
          description: "評価の種類"
    ViewEvaluation:
      type: object
      properties:
        sentence_id:
          type: integer
          format: int64
          description: "評価対象の投稿のID"
        evaluation_good_count:
          type: integer
          format: int64
          description: "Good評価の数"
        evaluation_stay_count:
          type: integer
          format: int64
          description: "Stay評価の数"
    Novel:
      type: object
      properties:
        title_id:
          type: integer
          format: int64
          description: "小説の一意のid（この値は他の小説と重複しない必要があります）"
        title:
          type: string
          description: "小説のタイトル"
        main_copy:
          type: string
          description: "小説の紹介文"
        author_user_id:
          type: integer
          format: int64
          description: "小説の作者のid"
        author_user_name:
          type: string
          description: "小説の作者のペンネーム"
        profile_icon_image:
          type: string
          description: "小説の作者のアイコン画像のurl"
        title_genres:
          type: array
          items:
            type: string
          description: "小説のジャンル"
        is_new:
          type: boolean
          description: "新着小説かどうか"
        is_famous:
          type: boolean
          description: "人気小説かどうか"
        view_count:
          type: integer
          description: "小説の閲覧数"
        created_at:
          type: string
          format: date-time
          description: "小説の作成日時"
        updated_at:
          type: string
          format: date-time
          description: "小説の修正日時"
    Novels:
      type: array
      items:
        $ref: "#/components/schemas/Novel"
    NovelOverview:
      allOf:
        - $ref: "#/components/schemas/Novel"
        - type: object
          properties:
            sentence_user_count:
              type: integer
              description: "小説に投稿された投稿の数"
            sentence_hierarchy_count:
              type: integer
              description: "小説に投稿された投稿の階層数"
            reader_count:
              type: integer
              description: "小説を読んだユーザーの数"
            overview:
              type: string
              description: "小説の概要"
    RegisterUser:
      type: object
      properties:
        email:
          type: string
          format: email
          description: "ユーザーのメールアドレス"
        google_sub:
          type: string
          maxLength: 128
          description: "Googleのサブジェクト識別子"
    RegisterUserResult:
      allOf:
        - $ref: "#/components/schemas/RegisterUser"
        - type: object
          properties:
            user_id:
              type: integer
              format: int64
              description: "ユーザーの一意のid"
            created_at:
              type: string
              format: date-time
              description: "ユーザーの作成日時"
