openapi: 3.0.0
info:
  title: Conovel API
  version: 1.0.0
servers:
  - url: /v1
paths:
  /sentences/{sentence_id}:
    get:
      tags:
        - sentences
      operationId: getSentenceById
      summary: Get a sentence by ID
      parameters:
        - name: sentence_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A single sentence
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ViewSentence"
        '404':
          description: Sentence not found
components:
  schemas:
    Sentence:
      type: object
      properties:
        sentence_id:
          type: integer
        sentence:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    Sentences:
      type: array
      items:
        $ref: "#/components/schemas/Sentence"
    ViewSentence:
      type: object
      properties:
        main:
          $ref: "#/components/schemas/Sentence"