openapi: 3.0.0
info:
  title: Sentences API
  version: 1.0.0
paths:
  /v1/sentences/{id}:
    get:
      summary: Get a sentence by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A single sentence
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  sentence:
                    type: string
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
        '404':
          description: Sentence not found