version: "3.9"

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: builder/frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    networks:
      - conobel-network

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: builder/backend/Dockerfile
    ports:
      - "8081:8081"
    networks:
      - conobel-network

  db:
    container_name: db
    build:
      context: .
      dockerfile: builder/db/Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - conobel-network

networks:
  conobel-network:
    driver: bridge