version: "3.9"
services:

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: builder/frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app #このファイルはどこにマウントされる？
      # - ./log/frontend/var_log:/var/log
      # - ./builder/frontend/entrypoint.sh:/usr/src/app/entrypoint.sh
    # environment:
      # - NODE_ENV=development
    depends_on:
      - backend
    # env_file:
      # - .env
    networks:
      - conobel-network
    # command: ["npm", "run", "web"]

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: builder/backend/Dockerfile
    ports:
      - "3010:3010"
    networks:
      - conobel-network
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app #このファイルはどこにマウントされる？
      # - ./log/backend/var_log:/var/log
      # - ./builder/backend/entrypoint.sh:/usr/src/app/entrypoint.sh
    # environment:
      # - RUBY_ENV=development
    # env_file:
    # - .env

  db:
    container_name: db
    build:
      context: .
      dockerfile: builder/db/Dockerfile
    # env_file:
      # - .env
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - conobel-network

networks:
  conobel-network:
    driver: bridge

volumes:
  db: