services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: builder/frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    networks:
      - conovel-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    # command: sh -c "vite --host --port ${PORT:-3000}"

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: builder/backend/Dockerfile
    ports:
      - "3001:3001"
    networks:
      - conovel-network
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DEVELOPMENT_ORIGIN_URL=${DEVELOPMENT_ORIGIN_URL}
      - PRODUCTION_ORIGIN_URL=${PRODUCTION_ORIGIN_URL}
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - swagger_data:/app/swagger
    command: sh -c "bundle exec rails db:migrate db:seed && bundle exec puma -C config/puma.rb"

  db:
    container_name: db
    build:
      context: .
      dockerfile: builder/db/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: myapp_development
      MYSQL_USER: ${MYAPP_DATABASE_USERNAME}
      MYSQL_PASSWORD: ${MYAPP_DATABASE_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - conovel-network
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf

networks:
  conovel-network:
    driver: bridge

volumes:
  db_data:
  swagger_data:
